services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: kanastra_backend
    environment:
      - PORT=3000
      - AWS_ENDPOINT=http://localhost:9000/kanastra-bucket
      - AWS_REGION=sa-east-1
      - AWS_ACCESS_KEY_ID=2J2z1TqWCShc1wYcwQsS
      - AWS_SECRET_ACCESS_KEY=mmpZsFc99jX7tQeZaypf56rhvQlAAKuR01kwpw9e
      - AWS_BUCKET=kanastra-bucket
      - RABBITMQ_KANASTRA_CONNECTION_STRING=amqp://admin:passw123@localhost:5672
      - RABBITMQ_STREAM_KANASTRA_CONNECTION_STRING=amqp://admin:passw123@localhost:5552
      - RABBITMQ_FILE_TOPIC_EXCHANGE=FILE_TOPIC
      - RABBITMQ_BILLET_TOPIC_EXCHANGE=BILLET_TOPIC
      - DATABASE_HOST=localhost
      - DATABASE_PORT=5432
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD="kanastra_password!"
      - DATABASE_SCHEMA=public
    ports:
      - '3000:3000'
    depends_on:
      - db
    volumes:
      - ./src:/app/src
  minio:
    image: quay.io/minio/minio
    container_name: minio_kanstra
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: kanastra_username
      MINIO_ROOT_PASSWORD: kanastra_password
    volumes:
      - ./minio/data:/data
    command: server /data --console-address ":9001"
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq_kanastra
    ports: 
    - 5672:5672
    - 15672:15672
    - 5552:5552
    
    environment:
    - RABBITMQ_DEFAULT_USER=admin
    - RABBITMQ_DEFAULT_PASS=passw123

    restart: always
  postgres:
    image: postgres
    container_name: postgres_kanastra
    environment:
      POSTGRES_PASSWORD: "kanastra_password!"      
    ports:
      - "5432:5432"