export const FILE_TOPIC_EXCHANGE = 'RABBITMQ_FILE_TOPIC_EXCHANGE';
export const BILLET_TOPIC_EXCHANGE = 'RABBITMQ_BILLET_TOPIC_EXCHANGE';
export const EXCHANGE_DEADLETTERS_NAME =
  'RABBITMQ_KANASTRA_EXCHANGE_DEADLETTERS_NAME';

export const STREAM_PROVIDER = 'STREAM_PROVIDER';
export const RABBITMQ_STREAM_NAME = String(
  process.env.RABBITMQ_STREAM_NAME || 'FILE_STREAM',
);

export const fileTopicExchangeName = String(
  process.env[FILE_TOPIC_EXCHANGE] || 'FILE_TOPIC',
);
export const billetTopicExchangeName = String(
  process.env[BILLET_TOPIC_EXCHANGE] || 'BILLET_TOPIC',
);
export const defaultDeadLettersExchangeName = String(
  process.env[EXCHANGE_DEADLETTERS_NAME] || 'KANASTRA_DEADLETTERS',
);

export const PROCESS_UPLOADED_FILE_USECASE = 'PROCESS_UPLOADED_FILE_USECASE';
export const PROCESS_GROUP_UPLOADED_FILE_USECASE =
  'PROCESS_GROUP_UPLOADED_FILE_USECASE';
export const PROCESS_BILLET_CHECK_PENDING_USECASE =
  'PROCESS_BILLET_CHECK_PENDING_USECASE';
