export interface MessagingEnviromentVariables {
  RABBITMQ_FILE_TOPIC_EXCHANGE: string;
  RABBITMQ_BILLET_TOPIC_EXCHANGE: string;
  RABBITMQ_KANASTRA_EXCHANGE_DEADLETTERS_NAME: string;
  RABBITMQ_KANASTRA_CONNECTION_STRING: string;
  RABBITMQ_KANASTRA_CONNECTION_WAIT: boolean;
  RABBITMQ_KANASTRA_CONNECTION_TIMEOUT: number;
  RABBITMQ_KANASTRA_PREFETCH_COUNT: number;
  RABBITMQ_KANASTRA_REGISTER_HANDLERS: boolean;
}
