export const UPLOADED_FILE_USECASE = 'UPLOADED_FILE_USECASE';
export const SET_UPLOAD_METADATA_USECASE = 'SET_UPLOAD_METADATA_USECASE';
export const SET_UPLOAD_FILENAME_USECASE = 'SET_UPLOAD_FILENAME_USECASE';
export const CHECK_FILE_CONTENT_TYPE_USECASE =
  'CHECK_FILE_CONTENT_TYPE_USECASE';
